[package]
name = "pack_pi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { version = "0.12.20", features = ["json"] }
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }
